CREATE TABLE IF NOT EXISTS chat (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL,
	message TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "user" (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL
);
